### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by bopaquin** [DCC-Lab/RayTracing#119]
While looking at my IDE, I've got hundreds of unused import reports from pylint when browsing the different files like `__main__.py`, `imagingpath.py`, `matrixgroup.py`, etc.

[Linting - pylint.txt](https://github.com/DCC-Lab/RayTracing/files/4653336/Linting.-.pylint.txt)

Shouldn't every file import only what they need?

**Comment by dccote** [comment]
Be specific so we can identify exactly what is meant here and reproduce/validate. Maybe paste the list of identified modules?

**Comment by dccote** [comment]
> [Linting - pylint.txt](https://github.com/DCC-Lab/RayTracing/files/4653336/Linting.-.pylint.txt)

A better description would describe how the pylon.txt was generated so we can repeat it on our computers.

`pylint ... blablalba`

**Comment by dccote** [comment]
Ok, this is definitely a low priority issue because we still have some bugs and some documentation issues weblike to work on before the publication. we can keep it, but it is a fairly tedious process.  Maybe we could do it on a few key files (such as `matrix.py` and `ray.py` for instance), but still, at a later time.

**Comment by dccote** [comment]
There is an Action (automatic script) that could run pylint every time someone pushes code.  **Once we have the code cleaned up**, we could install that.
https://github.com/marketplace/actions/github-action-for-pylint

**Comment by dccote** [comment]
This and #388 should be worked on together.
