### ISSUE TITLE
Matrix's backwardConjugate and forwardConjugate don't seem coherent in their outputs

### ISSUE THREAD

**Issue by GabGabG** [DCC-Lab/RayTracing#127]
`backwardConjugate()` returns `(None, None)` when `A == 0`, while `forwardConjugate()` returns `(float("+inf"), None)` when `D == 0`.

@dccote Is it normal? Should it be `(None, None)` or `(float("+/-inf"), None)` in both cases (for coherence)?

**Comment by dccote** [comment]
Let's go with +inf for now, but I think there is some ambiguity: if the limit is from zero+, we get +inf, but if it is from zero-, we would get -inf.  I think most people will understand and won't mind (it is at the limit between real and virtual image). I prefer to "favour" real images since it is likely what people would prefer.
