### ISSUE TITLE
Example : Add output histogram to widefield

### ISSUE THREAD

**Issue by Valeriouus** [DCC-Lab/RayTracing#233]
- See in branch fixExamplesDirectory, _widefield.py_

**Comment by Valeriouus** [comment]
What does distances mean?

**Comment by dccote** [comment]
I looked through it: 
1. I fixed the histogram (we do not need the angles histogram, it is not relevant).
2. I removed the `rayCount` function because I think it is simpler this way.
3.  I put the efficiency in the title of the graph
4. I increased the value of the second lens because we *had* vignetting... now we don't.
