### ISSUE TITLE
Is there a possibility to implement a Diffraction grating element?

### ISSUE THREAD

**Issue by millermuttu** [DCC-Lab/RayTracing#461]

**Comment by dccote** [comment]
It is not particularly easy because we currently don't consider wavelength explicitly.  It is hard to do so, because many elements are not wavelength dependent (Lens for instance). And introducing wavelength dependance requires some modifications because it means "focal spot" does not exist anymore.... because it becomes waveelngth dependent.  I will try to see how to introduce the dependence correctly.
