### ISSUE TITLE
Tests stop when testsAsynchronous is run

### ISSUE THREAD

**Issue by dccote** [DCC-Lab/RayTracing#80]
Incorrect, see comments below
The warnings package now makes the tests stop if a warning was issued.
There is a file called `env.py` that is imported in all tests.  There is a setting for the behaviour of warnings that can be set, and it should be added to `env.py`.

For instance, in the terminal, from the `tests` directory, running `python -m unittest` will stop at the first warning.

**Comment by GabGabG** [comment]
@dccote when I run ``python -m unittest`` in my terminal (with all test files), it also stops but not because of warnings. It stops because of tests in testsAsynchrnousTesting and testsMatplotlib.
![image](https://user-images.githubusercontent.com/25515426/81819822-d0dcf600-94fd-11ea-8992-a7321f0d76fd.png)


But when I remove said files, it works normally, even with warnings:
![image](https://user-images.githubusercontent.com/25515426/81819978-ff5ad100-94fd-11ea-86b7-4cdc7a66eb9e.png)


Can you run ``python -m unittest`` on my new branch fixWarnings? I only removed testsAsynchrnousTesting and testsMatplotlib and I would like to know if it works normally on your computer, because it does on mine.

**Comment by dccote** [comment]
> @dccote when I run `python -m unittest` in my terminal (with all test files), it also stops but not because of warnings. It stops because of tests in testsAsynchrnousTesting and testsMatplotlib.

You are 100% right. I merged master into your branch, fixed the conflates, and will merge back into master.

**Comment by dccote** [comment]
Was solved.
